### DISCUSSION TITLE
Handling Lack of Support for Cupy Structured Arrays

### DISCUSSION THREAD

**Discussion by fstrug** [scikit-hep/awkward#3517] [General]
# Problem
Support for structured arrays in `cupy` has been an open request since 2019 https://github.com/cupy/cupy/issues/2031. While it is possible to create a structured `cupy.ndarray`, once it is created you cannot interact with it in the same way as a `cupy.ndarray`. It is possible to copy back to the host as a `numpy.ndarray` and get the expected behavior.
```python
zeros_cupy = cp.zeros(shape=5, dtype=np.dtype([('index', '<i8'), ('tag', '<i4')]))
# index = zeros_cupy["index"] # ValueError: invalid literal for int() with base 10: 'index'

zeros_cupy_tonumpy = cupy.asnumpy(zeros_cupy)
index = zeros_cupy["index"]
```

In awkward, one can create an analogous awkward array with the cuda backend by calling
```python
ak_zeros_fromnumpy = ak.Array(np.zeros(shape=5, dtype=np.dtype([('index', '<i8'), ('tag', '<i4')])))
ak_zeros_fromnumpy_tocuda = ak.to_backend(ak_zeros_numpy, backend = "cuda") 
```
while calling
```python
ak_zeros_cupy = ak.Array(cp.zeros(shape=5, dtype=np.dtype([('index', '<i8'), ('tag', '<i4')])))
```
returns an error `TypeError: unsupported dtype: dtype([('index', '<i8'), ('tag', '<i4')])`.

# Potential Workaround

Since it is unclear what `cupy` will do in regards to this issue, it may be useful to provide a work around.

```python
import cupy as cp
import numpy as np
import awkward as ak

def get_RecordForm(array):
    dtypes = zeros_cupy.dtype
    fields = array.dtype.fields

    form = ak.forms.RecordForm(
        [ak.forms.NumpyForm(str(value[0]), form_key = "node{}".format(i+1)) 
         for i, value in enumerate(fields.values())],
        fields.keys(),
        form_key = "node0",
    )
    return form

def get_Container(array, form):
    container = {}
    fields = array.dtype.fields
    reshaped = array.view("uint8").reshape(-1,array.dtype.itemsize)
    tracker = 0
    for i, key in enumerate(zeros_cupy.dtype.fields.values()):

        form_key = form.contents[i].form_key
        data = reshaped[:,tracker:tracker+key[0].itemsize].view(key[0])
        tracker += key[0].itemsize
        container[f"{form_key}-data"] = data
    return(container)
        
        

def structured_cupy_toak(array):
    length = array.shape[0]
    form = get_RecordForm(array)
    container = get_Container(array, form)
    return ak.from_buffers(form, length, container, backend = "cuda")

zeros_cupy = cp.zeros(shape=5, dtype=np.dtype([('index', '<i8'), ('tag', '<i4')]))
ak_zeros_cupy = structured_cupy_toak(zeros_cupy)
print(ak_zeros_cupy)
```
This appears to give the same results as 
```python
zeros_numpy = np.zeros(shape=5, dtype=np.dtype([('index', '<i8'), ('tag', '<i4')]))
ak_zeros_numpy = ak.Array(zeros_numpy)
ak_zeros_cuda_fromnumpy = ak.to_backend(ak_zeros_numpy, backend = "cuda")
print(ak_zeros_cuda_fromnumpy)
```
but you get `CUDARuntimeError: cudaErrorMisalignedAddress: misaligned address` when you try to operate on the `awkward.Array` constructed directly from the `cupy.ndarray` slices. It would be nice to avoid bouncing the buffer back to the CPU if possible here, but that would require making contiguous copies from the slices? What are your thoughts here?

**Comment by fstrug** [comment]
@nsmith- @lgray

**Comment by ianna** [comment]
@fstrug - could you please try to 

```python

import cupy as cp
import numpy as np
import awkward as ak

def get_RecordForm(array):
    fields = array.dtype.fields

    form = ak.forms.RecordForm(
        [ak.forms.NumpyForm(str(value[0]), form_key=f"node{i+1}") 
         for i, value in enumerate(fields.values())],
        fields.keys(),
        form_key="node0",
    )
    return form

def get_Container(array, form):
    container = {}
    fields = array.dtype.fields
    reshaped = cp.ascontiguousarray(array.view("uint8")).reshape(-1, array.dtype.itemsize)
    tracker = 0

    for i, key in enumerate(fields.values()):
        form_key = form.contents[i].form_key
        data = reshaped[:, tracker:tracker + key[0].itemsize].view(key[0])
        tracker += key[0].itemsize
        container[f"{form_key}-data"] = cp.ascontiguousarray(data)  # Enforce alignment

    return container

def structured_cupy_to_ak(array):
    length = array.shape[0]
    form = get_RecordForm(array)
    container = get_Container(array, form)
    return ak.from_buffers(form, length, container, backend="cuda")
```

**Reply by fstrug** [reply]
It fails at `cp.ascontiguousarray(data): CUDADriverError: CUDA_ERROR_MISALIGNED_ADDRESS`. This is for cupy version 13.4.1.

**Reply by fstrug** [reply]
It seems that we must call `cp.ascontiguousarray()` before taking an alternate view on the slice of `reshaped`. Below works for me as expected and we get the contiguous buffers needed.

```python
import cupy as cp
import numpy as np
import awkward as ak

def get_RecordForm(array):
    fields = array.dtype.fields

    form = ak.forms.RecordForm(
        [ak.forms.NumpyForm(str(value[0]), form_key=f"node{i+1}") 
         for i, value in enumerate(fields.values())],
        fields.keys(),
        form_key="node0",
    )
    return form

def get_Container(array, form):
    container = {}
    fields = array.dtype.fields
    reshaped = cp.ascontiguousarray(array.view("uint8")).reshape(-1, array.dtype.itemsize)
    tracker = 0

    for i, key in enumerate(fields.values()):
        form_key = form.contents[i].form_key
        data = cp.ascontiguousarray(reshaped[:, tracker:tracker + key[0].itemsize]).view(key[0]) # Enforce alignment
        tracker += key[0].itemsize
        container[f"{form_key}-data"] = data  
    return container

def structured_cupy_to_ak(array):
    length = array.shape[0]
    form = get_RecordForm(array)
    container = get_Container(array, form)
    return ak.from_buffers(form, length, container, backend="cuda")
```

**Reply by ianna** [reply]
indeed, `.view()` slicing can lead to misaligned addresses...

**Comment by leofang** [comment]
@seberg is working on this on the CuPy side (https://github.com/cupy/cupy/issues/2031) so it'd be good to know the scope you'd like to see covered in CuPy 🙂

**Reply by ianna** [reply]
@leofang - Thanks for prioritizing it!

**Comment by kwamazibuko** [comment]
Good project

**Comment by ianna** [comment]
Hi @fstrug ! Could you please check where we are with this? Thanks.

**Reply by seberg** [reply]
FYI, for the dtype above, which NumPy packs by default and which may have different alignment on the GPU (cupy doesn't implement support for unaligned datatypes), you may need the `cp.make_aligned_dtype()` utility to make it work.
(Many paths should give an error that points to it I think, but for some paths I am not sure, they might just crash CUDA with an "unaligned memory access" error.)
